[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["ThatFulvioGuy"]
publish = false

[dependencies]
image = "0.17"

[profile.dev]
opt-level = 1

[workspace]
members = ["mandelbrot-bin", "mandelbrot-wasm"]
