
env:
  browser: true
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended

parser: babel-eslint
parserOptions:
  sourceType: module

rules:
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - off
  react/no-deprecated:
    - off # Erroneously complains about preact.render
  react/prop-types:
    - off # Not used in preact
